# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'NanoBlocks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for NanoBlocks
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'NotificationBannerSwift', '1.6.3'
  pod 'Moya', '~> 11.0'
  pod 'lottie-ios'
  pod 'SSZipArchive'
  pod 'CocoaMQTT'
  pod 'PromisesSwift', '~> 1.2.3'
  pod 'Sodium', :git => 'https://github.com/nebyark/swift-sodium.git'
  #pod "mantaswift", :path => '/Users/avigano/Developer/mantaProtocolUI'
  pod "mantaswift", :git => 'https://github.com/NanoRay/mantaswift'
end

target 'NanoBlocksTests' do
  use_frameworks!
  pod 'RealmSwift'
end

